// Typelizer digest 9b0226f38ddd00bbaf500a1431085336
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /settings/email */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/settings/email', {}, options),
    method: 'get',
  }),

  /** PATCH /settings/email */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/settings/email', {}, options),
    method: 'patch',
  }),
}
