// Typelizer digest 566c9937e4bbb2c66a22a1b1b644e5e4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /settings/password */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/settings/password', {}, options),
    method: 'get',
  }),

  /** PATCH /settings/password */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/settings/password', {}, options),
    method: 'patch',
  }),
}
