// Typelizer digest 267e91979e3f6e0ab9dba46923a0e7f0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /settings/profile */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/settings/profile', {}, options),
    method: 'get',
  }),

  /** PATCH /settings/profile */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/settings/profile', {}, options),
    method: 'patch',
  }),
}
