// Typelizer digest 7efd5d7624682932932c33a1d4af59b2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /drawing_plans/:drawing_plan_id/generation */
  show: (
    params: { drawingPlanId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/drawing_plans/:drawing_plan_id/generation', params, options),
    method: 'get',
  }),

  /** POST /drawing_plans/:drawing_plan_id/generation */
  create: (
    params: { drawingPlanId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/drawing_plans/:drawing_plan_id/generation', params, options),
    method: 'post',
  }),
}
