// Typelizer digest 5a6f928d437007347f13f80999056fe6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /identity/email_verification */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/identity/email_verification', {}, options),
    method: 'get',
  }),

  /** POST /identity/email_verification */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/identity/email_verification', {}, options),
    method: 'post',
  }),
}
