// Typelizer digest a52d87b0471f57239a58e905d756c85c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /identity/password_reset/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/identity/password_reset/new', {}, options),
    method: 'get',
  }),

  /** GET /identity/password_reset/edit */
  edit: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/identity/password_reset/edit', {}, options),
    method: 'get',
  }),

  /** PATCH /identity/password_reset */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/identity/password_reset', {}, options),
    method: 'patch',
  }),

  /** POST /identity/password_reset */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/identity/password_reset', {}, options),
    method: 'post',
  }),
}
