// Typelizer digest bce3e4860665e6e06128b7516df8de34
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /active_profile */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/active_profile', {}, options),
    method: 'get',
  }),

  /** PATCH /active_profile */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/active_profile', {}, options),
    method: 'patch',
  }),
}
