// Typelizer digest 9ab01df81a75e136042c841bea4dd8e7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /dashboard */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/dashboard', {}, options),
    method: 'get',
  }),
}
