// Typelizer digest 42d4d11a42afd80ec1eff5c1a085da3d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /directed_drawings */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/directed_drawings', {}, options),
    method: 'get',
  }),

  /** GET /directed_drawings/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/directed_drawings/:id', params, options),
    method: 'get',
  }),
}
