// Typelizer digest fb27b564b97dc860df29cccecec1526e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /drawing_plans */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/drawing_plans', {}, options),
    method: 'post',
  }),

  /** GET /drawing_plans/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/drawing_plans/:id', params, options),
    method: 'get',
  }),

  /** PATCH /drawing_plans/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/drawing_plans/:id', params, options),
    method: 'patch',
  }),
}
