// Typelizer digest 096e862664ef5a91951880c91983f063
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /profiles */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/profiles', {}, options),
    method: 'get',
  }),

  /** POST /profiles */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/profiles', {}, options),
    method: 'post',
  }),

  /** GET /profiles/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/profiles/new', {}, options),
    method: 'get',
  }),

  /** GET /profiles/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/profiles/:id/edit', params, options),
    method: 'get',
  }),

  /** PATCH /profiles/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/profiles/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /profiles/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/profiles/:id', params, options),
    method: 'delete',
  }),
}
