// Typelizer digest 719d37f71b26dda57baf1a3db6137bb8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /settings/appearance */
  settingsAppearance: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/settings/appearance', {}, options),
    method: 'get',
  }),
}
