// Typelizer digest 9ceb2d9574153b2772e12c27d9c174d9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /sign_in */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/sign_in', {}, options),
    method: 'get',
  }),

  /** POST /sign_in */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/sign_in', {}, options),
    method: 'post',
  }),

  /** DELETE /sessions/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/sessions/:id', params, options),
    method: 'delete',
  }),
}
