// Typelizer digest 496fb69d0f80a6f47f8bfffa6dc727dc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /sign_up */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/sign_up', {}, options),
    method: 'get',
  }),

  /** POST /sign_up */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/sign_up', {}, options),
    method: 'post',
  }),

  /** DELETE /users */
  destroy: (options?: RouteOptions): RouteDefinition<'delete'> => ({
    url: buildUrl('/users', {}, options),
    method: 'delete',
  }),
}
