// Typelizer digest 94807996166e2ca2706c3356fc1fc7a0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /directed_drawings/:directed_drawing_id/artworks */
  create: (
    params: { directedDrawingId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/directed_drawings/:directed_drawing_id/artworks', params, options),
    method: 'post',
  }),
}
