// Typelizer digest 48ea41655bd355f496e0da933a14e8e0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /directed_drawings/:directed_drawing_id/confirmation */
  create: (
    params: { directedDrawingId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/directed_drawings/:directed_drawing_id/confirmation', params, options),
    method: 'post',
  }),
}
