// Typelizer digest 97e78e7f40f2f703219ca7c74a75b2e5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** PATCH /directed_drawings/:directed_drawing_id/current_step */
  update: (
    params: { directedDrawingId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/directed_drawings/:directed_drawing_id/current_step', params, options),
    method: 'patch',
  }),
}
