// Typelizer digest b3207df6cf2ce7aa848a1443f8d22076
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /directed_drawings/:directed_drawing_id/repeat */
  create: (
    params: { directedDrawingId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/directed_drawings/:directed_drawing_id/repeat', params, options),
    method: 'post',
  }),
}
